use ingot::PIECE_EMPTY

pub fn sq_file(_ sq: u8) -> u8 {
    sq & 7
}

pub fn sq_rank(_ sq: u8) -> u8 {
    sq >> 3
}

pub fn sq(_ file: u8, _ rank: u8) -> u8 {
    file + (rank * 8)
}

pub fn abs_diff(_ a: u8, _ b: u8) -> u8 {
    if a >= b {
        a - b
    } else {
        b - a
    }
}

pub fn max_u8(_ a: u8, _ b: u8) -> u8 {
    if a >= b { a } else { b }
}

pub fn is_empty(_ piece: u8) -> bool {
    piece == PIECE_EMPTY
}

pub fn is_white_piece(_ piece: u8) -> bool {
    piece != PIECE_EMPTY && piece < 8
}

pub fn is_black_piece(_ piece: u8) -> bool {
    piece >= 8
}

pub fn same_color(_ a: u8, _ b: u8) -> bool {
    if is_empty(a) || is_empty(b) {
        false
    } else {
        (is_white_piece(a) && is_white_piece(b)) || (is_black_piece(a) && is_black_piece(b))
    }
}

pub fn piece_kind(_ piece: u8) -> u8 {
    piece & 0x7
}
